"""create core tables

Revision ID: 0d4a33b78d55
Revises: 
Create Date: 2025-12-27 13:46:38.870167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d4a33b78d55'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('s3_bucket', sa.String(length=255), nullable=False),
    sa.Column('s3_key', sa.String(length=1024), nullable=False),
    sa.Column('s3_url', sa.String(length=2048), nullable=False),
    sa.Column('file_type', sa.String(length=32), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('REGISTERED', 'PROCESSING', 'INDEXED', 'FAILED', name='document_status'), server_default='REGISTERED', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('s3_bucket', 's3_key', name='uq_documents_bucket_key')
    )
    op.create_index('idx_documents_status', 'documents', ['status'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_chunks_doc_chunkindex')
    )
    op.create_index('idx_chunks_document_id', 'chunks', ['document_id'], unique=False)
    op.create_table('document_artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('artifact_type', sa.String(length=64), nullable=False),
    sa.Column('s3_url', sa.String(length=2048), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_artifacts_document_id', 'document_artifacts', ['document_id'], unique=False)
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Enum('extract', 'chunk', 'embed', 'index', name='job_stage'), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_jobs_document_id', 'ingestion_jobs', ['document_id'], unique=False)
    op.create_index('idx_jobs_stage', 'ingestion_jobs', ['stage'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_jobs_stage', table_name='ingestion_jobs')
    op.drop_index('idx_jobs_document_id', table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_index('idx_artifacts_document_id', table_name='document_artifacts')
    op.drop_table('document_artifacts')
    op.drop_index('idx_chunks_document_id', table_name='chunks')
    op.drop_table('chunks')
    op.drop_index('idx_documents_status', table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
